# Generated by Django 5.1.1 on 2024-10-10 18:41

import SouTOCA.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_esportes',
            fields=[
                ('esp_id', models.AutoField(primary_key=True, serialize=False)),
                ('esp_nome', models.CharField(max_length=255)),
                ('esp_img', models.ImageField(blank=True, upload_to='SouTOCA/static/sport_images/', validators=[functools.partial(SouTOCA.models.validate_image_size, *(), **{'max_size_mb': 10})])),
            ],
        ),
        migrations.CreateModel(
            name='tb_imagens',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_conteudo', models.ImageField(upload_to='SouTOCA/static/images/')),
                ('img_alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_usuarios',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nome', models.CharField(max_length=255)),
                ('usr_email', models.EmailField(max_length=255)),
                ('usr_senha', models.CharField(max_length=255)),
                ('usr_imagem', models.ImageField(blank=True, upload_to='SouTOCA/static/user_images/', validators=[functools.partial(SouTOCA.models.validate_image_size, *(), **{'max_size_mb': 2})])),
                ('usr_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_noticias',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('not_titulo', models.CharField(max_length=255)),
                ('not_conteudo', models.TextField()),
                ('not_publishDate', models.DateField()),
                ('not_image', models.ImageField(blank=True, upload_to='SouTOCA/static/sport_images/', validators=[functools.partial(SouTOCA.models.validate_image_size, *(), **{'max_size_mb': 10})])),
                ('not_esp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_esportes')),
                ('not_img_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_imagens')),
                ('not_usr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='tb_docentes',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_matricula', models.CharField(max_length=255)),
                ('doc_usr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='tb_comentarios',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_conteudo', models.TextField(max_length=255)),
                ('com_publishDate', models.DateField()),
                ('com_not_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_noticias')),
                ('com_usr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='tb_atletas',
            fields=[
                ('atl_id', models.AutoField(primary_key=True, serialize=False)),
                ('atl_turma', models.CharField(max_length=255)),
                ('atl_idade', models.IntegerField()),
                ('atl_bio', models.TextField()),
                ('atl_esp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_esportes')),
                ('atl_usr_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SouTOCA.tb_usuarios')),
            ],
        ),
    ]
